[PLAT788] Add isFree to billing status type
tozny/js-account-sdk pull request #65
Opened 2021-11-18 18:36 UTC by carrala

2021-11-18 19:08 UTC, galxy25 approved these changes

2021-11-18 23:53 UTC, house9 approved these changes
I think we might want to update api-specs for this as well:

Pretty sure this is it?
https://github.com/tozny/api-specs/blob/master/billing/swagger.yml#L240

2021-11-22 16:10 UTC, pirtleshell commented on src/types/accountBillingStatus.js
> +    isFree
`isFree` should either come before the param that has a default value or should be given a valid default value itself. i'm not sure why `isGoodStanding` defaults to `null` but someone made that choice on purpose and it should be respected (ie we should be able to set `isFree` without needing to know the default value of `isGoodStanding`)

i'd be tempted to just default `isFree` to `null` as well. likely to distinguish between it being unset from being false.

2021-11-22 16:13 UTC, pirtleshell requested changes

2021-11-22 16:13 UTC, pirtleshell commented on src/types/accountBillingStatus.js
> +    isFree
`isFree` should either be before `isGoodStanding` or be given a default value itself. not sure why `isGoodStanding` defaults to `null`, but someone made that choice on purpose and we should respect that. ie. we should be able to set `isFree` without knowing `isGoodStanding`.

i'd recommend just defaulting `isFree` to `null` as well. it was likely done for historical reasons to distinguish it being unset from it being false

2021-11-22 17:03 UTC, pirtleshell approved these changes

2021-11-22 18:56 UTC, merged